---
title: "Crosswalking play file"
output: html_document
date: "2024-07-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(pacman)


p_load(tidycensus,tidyverse,sf,data.table,tigris,
       srvyr,survey,rio,car,janitor,rmapshaper,scales,santoku,viridis, urbnmapr, usmap, ipumsr, dplyr, readr, terra)

```


```{r}
crosswalk_geom <- function(shapefile, data, source_scale, target_scale) {
  
  # Use case: Assign point data or smaller polygons to the target scale based on the larger polygons they are        # contained in. Uses st_contains to check if shape contained by another.
  
  # Args: 
    # shapefile: shapefile containing polygons
    # data: shapefile containing polygons OR data with latitude and longitude columns (can be converted to sf)
    # source_scale: a list. the column name(s) of the source scale e.g c("latitude", "longitude") or c("geometry")
    # target_scale: the name (str) of the target column name e.g ("geometry")
  
  # Output: 
    # One joined dataset on the target scale

    require(sf)
    # Transform data to the CRS of the target polygons

  if (st_crs(data_sf) != st_crs(shapefile)) {
    stop("CRS of data and shapefile do not match even after transformation.")
  }
  
  # Perform the spatial join to check containment
  joined_data <- st_join(data_sf, shapefile, largest = TRUE)
  
  
  # Return the joined dataset
  return(joined_data)
}

```

## Testing CWNS example (points and counties shapefile)
# Counties in new column of joined dataframe should match existing county column from cwns dataset
```{r}
# Try to find bug for this error message: Warning in st_is_longlat(x): bounding box has potentially an invalid value range for longlat data

# Check type cwns type of data after transformation to sf, is the bounding box the geom column? 


```

```{r}

options(tigris_use_cache = TRUE)
# Load the counties shapefile for the entire United States
counties_sf <- counties(year = 2023, cb = TRUE)

cwns <- read_csv("~/Downloads/cwns-flow.csv")
cwns <- cwns %>% 
  select(COUNTY_FIPS, LATITUDE, LONGITUDE, CURRENT_DESIGN_FLOW, LOCATION_TYPE)

head(cwns)

cwns_sf <- st_as_sf(cwns, coords = c("LONGITUDE", "LATITUDE"), crs = st_crs(counties_sf))

cwns_sf$geometry

counties_sf$geometry


```

```{r}
#general conversion from csv and excel sheet containing latitude and longitude columns to shapefile 
convert_to_shapefile <- function(data, location_columns, crs){
  #Args: 
    # data: a csv or excel spreadsheet containing latitude and longitude columns
    # 
  cwns_sf <- st_as_sf(cwns, coords = , crs = st_crs(counties_sf))

cwns_sf$geometry

counties_sf$geometry
}

```

```{r}

cwns_joined_data <- crosswalk_geom(counties_sf, cwns_sf, c("geometry"), "geometry")
cwns_joined_data
```
## Testing Interbasin Water Transfers Example (lines in counties shapefile)
# Lines should be new counties column should be populated in addition to existing state and country columns from ibt dataset
```{r}
ibt <- read_sf(dsn = '~/Downloads/IBT Geospatial Data/', layer = "Digitized_IBTs")
head(ibt)
```


```{r}

options(tigris_use_cache = TRUE)

# Load the counties shapefile for the entire United States
counties_sf <- counties(year = 2023, cb = TRUE)

ibt <- st_as_sf(ibt, crs = st_crs(counties_sf))
ibt <- st_transform(ibt, crs = st_crs(counties_sf))

ibt_joined_data <- crosswalk_geom(counties_sf, ibt, c("geometry"), "geometry")
head(ibt_joined_data)

```

