---
title: "county_level_mapping"
author: "Daniel Vogler"
date: "2024-07-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ipumsr)
library(dplyr)
library(readxl)
library(usmap)
library(dplyr)
library(tigris)
library(sf)
library(stringr)
library(ggplot2)
```

```{r}
census_year <- 2020

counties <- counties(year=census_year) %>% st_transform(crs = 3082)
```

```{r}
root_dir <- config::get()
datasets_folder <- "/Drivers/multiyear drought risk/"

dataset_dir <- paste0(root_dir, datasets_folder)
print(file.exists(dataset_dir))

filename <- "final_results_dissemination_NDINDC.xlsx"

filepath <- paste0(dataset_dir, filename)

data <- read_xlsx(filepath, sheet=1) %>% 
  mutate(FIPS = as.character(FIPS))
```

```{r}
counties <- counties %>% 
  mutate(GEOID = str_trim(GEOID)) %>%
  mutate(GEOID = ifelse(nchar(GEOID) == 0, "0", GEOID)) %>%
  mutate(GEOID = as.character(GEOID)) %>% 
  rename(FIPS = GEOID)
```

```{r}
data_sf <- counties %>% left_join(data, by="FIPS") %>% 
  mutate(NDI = as.numeric(NDI))
```

```{r}
ggplot(data = data_sf) +
  geom_sf(aes(fill = NDI)) +
  scale_fill_gradient(low = "lightgrey", high = "red", na.value = "white") +
  theme_minimal() +
  labs(
    title = "Drought Risk by US County, 2009",
    fill = "Drought Risk"
  )
```

```{r}
ggplot(data = data_sf) +
  geom_sf(aes(fill = NDI)) +
  scale_fill_viridis_c(option = "plasma") +  # Optional: Change color scale
  theme_minimal() +
  labs(
    title = "Choropleth Map of US Counties",
    fill = "Value to Map"
  )
```

```{r}
plot_percentile <- function(data, variable, caption, title,
                            percentile=0.95,
                            low_color = "white", high_color = "red",
                            na_color = "gray"){
  percentiles <- quantile(data[[variable]], probs=c(0, percentile), na.rm=TRUE)
  plot_data_variable <- ggplot(data)+
    geom_sf(mapping = aes_string(fill = variable)) +
    scale_fill_gradient(name = variable,
                        label = scales::comma_format(),
                        low=low_color,
                        high=high_color,
                        na.value = na_color,
                        limits = percentiles,
                        breaks = scales::pretty_breaks(n = 5)) +
    labs(title = title,
         caption = caption) +
    theme(text = element_text(family = "Times New Roman"))
      return(plot_data_variable)
}

plot_percentile(data = data_plot,
                variable = "NDC",
                title = "NDC by county",
                caption = "NDC is the cumulative deficit over 1949-2010.")
```