# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG Project Name
tagline:          ''
description:      'A 2024 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/WaterReuseDSSG2024"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/WaterReuseDSSG2024/
