---
title: "county_level_mapping"
author: "Daniel Vogler"
date: "2024-07-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

setwd("/Users/danielvogler/Documents/DSSG/WaterReuseDSSG2024")

library(ipumsr)
library(dplyr)
library(readxl)
library(usmap)
library(dplyr)
library(tigris)
library(sf)
library(stringr)
library(ggplot2)
library(urbnmapr)

source("/Users/danielvogler/Documents/DSSG/WaterReuseDSSG2024/map_utils/map_utils.R")
```

```{r}
counties <- get_urbn_map(map = "counties", sf=TRUE) %>%
  filter(!(state_abbv %in% c("HI", "AK")))
```

```{r}
root_dir <- config::get()
datasets_folder <- "/Drivers/multiyear drought risk/"

dataset_dir <- paste0(root_dir, datasets_folder)
print(file.exists(dataset_dir))

filename <- "final_results_dissemination_NDINDC.xlsx"

filepath <- paste0(dataset_dir, filename)

data <- read_xlsx(filepath, sheet=1) %>% 
  mutate(FIPS = as.character(FIPS)) %>% 
  mutate(FIPS = sub("^0+", "", FIPS))
```

```{r}

## TO DO: consider how to deal with leading zeros
counties <- counties %>% 
  rename(FIPS = county_fips) %>%
  mutate(FIPS = sub("^0+", "", FIPS))
```

```{r}
data_sf <- counties %>% left_join(data, by="FIPS") %>% 
  mutate(NDI = as.numeric(NDI))
```

```{r}
map_choropleth(data = data_sf, 
                shapefile = NULL, 
                data_key = "FIPS", 
                shape_key = NULL, 
                variable = "NDI",
                map_percentile = TRUE)
```