check_compatibility <- function(data, shapefile, data_key, shape_key) {
  
  # Two checks are needed:
  # - data_key is a column in data & shape_key is a column in shapefile
  # - data_key and shape_key have the same type
  
  # Output: boolean - true if this combination of data, shapefile, keys
  # can be spatially joined
  
  check_result <- data_key %in% names(data) && 
    shape_key %in% names(shapefile) && 
    type(data_key) == typeof(shape_key)
  
  return (check_result)
  
}

map_chloropleth <- function(data, shapefile, data_key, shape_key, value) {
  
  # Inputs:
  # data - dataset from which the user wants to map a variable
  # shapefile - the shapefile specifying the shapes defining regions in the map
  # data_key - the column from the dataset that should be used to join them
  # shape_key - the column from the shapefile that should be used to join them
  # value - the variable which the user wants to visualize on the map
  
  # Outputs:
  # chloropleth map generated by ggplot2 of the designated variable
  
  if (check_compatibility(data, shapefile, data_key, shape_key) == FALSE) {
    warning("Warning: data and shapefile may not be compatible.\n
            Please check that the two key columns have the same data type.")
  }
  
  
}